### Пример 1

### Было

```kotlin

fun getProfileData() {
    viewModelScope.launch {
        try {
            val profileData = getProfileDataUseCase()
            _profileDataState.emit(ProfileDataUI.fromProfileData(profileData))
        } catch (e: Exception) {
            e.printStackTrace()
        }

    }
}

class ProfileDataRepositoryImpl @Inject constructor(
    private val profileDataApi: ProfileDataApi
): ProfileDataRepository {
    override suspend fun getProfileData(): ProfileData {
        return profileDataApi.getProfileData().first().toModel()
    }

}

```

### Стало

```kotlin

class ProfileDataRepositoryImpl @Inject constructor(
    private val profileDataApi: ProfileDataApi,
    private val defaultDispatcher: CoroutineDispatcher,
): ProfileDataRepository {
    
    override suspend fun getProfileData(): Flow<Result<ProfileData>> = flow {
        emit(Result.Loading)
        val result = profileDataApi.getProfileData().first().toModel()
        emit(Result.Success(result))
    }.catch {
        emit(Result.Failure(it.fillInStackTrace()))
    }.flowOn(defaultDispatcher)

}

sealed class Result<out T> {
    object Loading : Result<Nothing>()
    class Failure(val msg: Throwable) : Result<Nothing>()
    class Success<T>(val data: T) : Result<T>()
    object Empty : Result<Nothing>()
}

fun getProfileData() {
    getProfileDataUseCase().onEach {
        when (it) {
            is Result.Success -> emitProfileData(it.data)
            is Result.Failure -> printError(it.msg.localizedMessage)
            is Result.Loading -> processLoading()
            is Result.Empty -> processEmptyResult()
        }
    }.launchIn(viewModelScope)
}

fun emitProfileData(profileData: ProfileData){}

fun printError(message: String?){}

fun processLoading(){}

fun processEmptyResult(){}

```

Добавил строго определенное множество ситуаций